[package]
name = "dueling_bandits_simulator"
version = "0.1.0"
authors = ["Ryosuke Ishizue <ryoskate@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
